version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 80:3000
    env_file:
      - .env

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
