- hosts: all
  remote_user: root

  vars_files:
    - group_vars/vars.yml

  tasks:
    - name: Install pip
      apt:
        update_cache: yes
        name:
          - python3-pip

    - name: include role
      include_role:
        name: geerlingguy.pip
